# Generated by Django 6.0.5 on 2026-08-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_switch_to_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeorder',
            name='service_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
